import type { Metadata } from "next";
import { Geist, Rajdhani } from "next/font/google";
import AnimateTransition from "@/components/AnimateTransition";
import Navbar from "@/components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nikhil Mishra",
  description: "Generated by Nikhil Mishra",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased tracking-tight min-h-screen ${outfit.className}`}
      >
        {/* <AnimateTransition> */}
          <Navbar />

          {children}
        {/* </AnimateTransition> */}
      </body>
    </html>
  );
}
