import type { Metadata } from "next";
import { Geist, Rajdhani } from "next/font/google";
import "./globals.css";
// import LoaderGate from "@/components/LoaderGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Rajdhani({
  subsets: ['latin'], // Specifies character subsets
  weight: ['400', "500",  '600', "700"], // Include the desired font weights
});

export const metadata: Metadata = {
  title: "Nikhil's Portfolio",
  description: "Generated by Nikhil Mishra",
  icons: {
    icon: '/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased tracking-tight min-h-screen ${outfit.className}`}
      >
        {/* <LoaderGate /> */}
        {children}
      </body>
    </html>
  );
}
